### ISSUE TITLE
Can't use psda.vmf

### ISSUE THREAD

**Issue by hussenmoh12** [bsxfan/PSDA#2]
ModuleNotFoundError: No module named 'psda.vmf'; 'psda' is not a package

**Comment by bsxfan** [comment]
I have renamed `psda.psda` --> `psda.psdamodel`. I have tested the new code on examples\demo and examples\calibration_demo and they run correctly.

**Comment by hussenmoh12** [comment]
It is still not working


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by hussenmoh12** [comment]
How can I use your code to apply speaker identification
Technology on my app

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by bsxfan** [comment]
Can you give more details please, for example a stacktrace.

Niko
